# Generated by Django 3.0.6 on 2020-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listi_ng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('agent', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('SqFt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bathroom', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
            ],
        ),
    ]
