# Generated by Django 3.0.6 on 2020-05-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listi_ng',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listi_ng'),
        ),
    ]
