# Generated by Django 3.0.6 on 2020-05-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200521_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='listi_ng',
            name='street_img',
            field=models.ImageField(blank=True, upload_to='media/agent_img/%Y/%m/%d/'),
        ),
    ]
