# Generated by Django 3.0.6 on 2020-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listi_ng_street_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listi_ng',
            name='SqFt',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
        migrations.AlterField(
            model_name='listi_ng',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
    ]
