# Generated by Django 3.0.6 on 2020-05-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20200521_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='listi_ng',
            name='detail',
            field=models.CharField(default='op', max_length=2000),
        ),
    ]
