# Generated by Django 3.0.6 on 2020-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listi_ng_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listi_ng',
            name='street_img',
            field=models.ImageField(blank=True, upload_to='agent_img/%Y/%m/%d/'),
        ),
    ]
