# Generated by Django 3.0.6 on 2020-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20200528_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listi_ng',
            name='street_img',
            field=models.ImageField(blank=True, upload_to='property_img/%Y/%m/%d/'),
        ),
    ]
