# Generated by Django 3.0.6 on 2020-05-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_listi_ng_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listi_ng',
            old_name='detail',
            new_name='detail1',
        ),
    ]
